workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build APK directly
        script: gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
