workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m1
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
